7zip
alacritty
base
base-devel
btop
docker
ecryptfs-utils
eza
f2fs-tools
fd
firefox
flatpak-builder
fwupd
grub
grub-btrfs
gtk3
htop
ipcalc
jupyterlab
less
lib32-libcanberra
lib32-libva-intel-driver
lib32-libva-vdpau-driver
lib32-mesa-utils
lib32-nvidia-utils
lib32-vulkan-intel
lib32-vulkan-nouveau
lib32-vulkan-radeon
libcanberra
libdvdcss
libpamac-flatpak-plugin
libreoffice-still
libva-intel-driver
libva-vdpau-driver
libxnvctrl
man-db
man-pages
mdadm
memtest86+
memtest86+-efi
modemmanager
mtr
nano
nano-syntax-highlighting
neofetch
neovim
network-manager-applet
noto-fonts
noto-fonts-cjk
noto-fonts-emoji
nvidia-container-toolkit
nvidia-prime
nvidia-settings
nvidia-utils
openresolv
openssh
os-prober
plocate
plymouth
powertop
python-pillow
python-pip
python-pysmbc
python-reportlab
reiserfsprogs
sshfs
stow
sudo
sysfsutils
tcpdump
terminator
terminus-font
texinfo
tmux
traceroute
ttf-dejavu
ttf-droid
ttf-inconsolata
ttf-indic-otf
ttf-liberation
update-grub
vi
vim
vlc
vulkan-intel
vulkan-nouveau
vulkan-radeon
wget
which
wireshark-qt
zlib-ng
